#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0xCA (0x16A - 0xA0)
// BlueprintGeneratedClass BP_HazardMaterialComponent.BP_HazardMaterialComponent_C
class UBP_HazardMaterialComponent_C : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xA0(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	TMap<class FName, struct FS_HazardStatus>    Active_Status_Effects;                             // 0xA8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class FName, struct FS_HazardAccumulation> AccumulationGauges;                                // 0xF8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UHazardMaterialDataAsset_C*            Hazard_Data_Asset;                                 // 0x148(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                          AccumulationTimerHandle;                           // 0x150(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UNWXPhyiscalMaterial*                  LastFloor;                                         // 0x158(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ABP_Character_C*                       As_BP_Character;                                   // 0x160(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                         bIsWading;                                         // 0x168(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         bIsSwimming;                                       // 0x169(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UBP_HazardMaterialComponent_C* GetDefaultObj();

	void CheckHazards(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_GetCurrentRealmTags_Success, const struct FGameplayTagContainer& CallFunc_GetCurrentRealmTags_RealmTags, bool CallFunc_IsValid_ReturnValue, bool CallFunc_K2_IsValidTimerHandle_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const struct FS_HazardMaterial& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool K2Node_MathExpression_ReturnValue, bool CallFunc_HasAllTags_ReturnValue, int32 CallFunc_GetNumGameplayTagsInContainer_ReturnValue, bool CallFunc_HasAllTags_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_GetNumGameplayTagsInContainer_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue_1, const struct FS_HazardAccumulation& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FS_HazardAccumulation& K2Node_SetFieldsInStruct_StructOut, const struct FS_HazardAccumulation& CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, const struct FS_HazardAccumulation& K2Node_SetFieldsInStruct_StructOut_1);
	void UpdateSwimmingWadingState(bool Wading, bool Swimming, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_HasAuthority_ReturnValue);
	class FName StatusToAccumulationName(class FName InName, const class FString& CallFunc_Conv_NameToString_ReturnValue, const class FString& CallFunc_Split_LeftS, const class FString& CallFunc_Split_RightS, bool CallFunc_Split_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue);
	void ApplyStatusEffects(TArray<class UStatusEffectDataAsset*>& Status_Effects, class FName Key, double Duration, int32 Temp_int_Array_Index_Variable, bool CallFunc_Less_DoubleDouble_ReturnValue, class UStatusEffectDataAsset* CallFunc_Array_Get_Item, const class FString& CallFunc_Conv_IntToString_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, class FName CallFunc_Conv_StringToName_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, int32 Temp_int_Loop_Counter_Variable, TScriptInterface<class IStatusEffectAccessInterface> K2Node_DynamicCast_AsStatus_Effect_Access_Interface, bool K2Node_DynamicCast_bSuccess, const struct FStatusEffectHandle& CallFunc_ApplyTimedStatusEffect_ActiveStatusEffectHandle, bool CallFunc_ApplyTimedStatusEffect_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FS_HazardStatus& K2Node_MakeStruct_S_HazardStatus, int32 CallFunc_Add_IntInt_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, class AActor* CallFunc_GetOwner_ReturnValue_2, TScriptInterface<class IStatusEffectAccessInterface> K2Node_DynamicCast_AsStatus_Effect_Access_Interface_1, bool K2Node_DynamicCast_bSuccess_1, TScriptInterface<class IStatusEffectAccessInterface> K2Node_DynamicCast_AsStatus_Effect_Access_Interface_2, bool K2Node_DynamicCast_bSuccess_2, const struct FS_HazardStatus& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_3, TScriptInterface<class IStatusEffectAccessInterface> K2Node_DynamicCast_AsStatus_Effect_Access_Interface_3, bool K2Node_DynamicCast_bSuccess_3, const struct FStatusEffectHandle& CallFunc_ApplyInfiniteStatusEffect_ActiveStatusEffectHandle, bool CallFunc_ApplyInfiniteStatusEffect_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, const struct FS_HazardStatus& K2Node_MakeStruct_S_HazardStatus_1, bool CallFunc_IsStatusEffectInstanceValid_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, float CallFunc_ApplyTimedStatusEffect_Duration_ImplicitCast);
	void AccumulationIncrement(bool FoundActive, float TimerPeriod, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_Not_PreBool_ReturnValue, TArray<struct FS_HazardAccumulation>& CallFunc_Map_Values_Values, const struct FS_HazardAccumulation& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, TScriptInterface<class IAccumulationAccessInterface> K2Node_DynamicCast_AsAccumulation_Access_Interface, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, TArray<struct FS_HazardAccumulation>& CallFunc_Map_Values_Values_1, const struct FS_HazardAccumulation& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, const struct FS_HazardAccumulation& K2Node_SetFieldsInStruct_StructOut, bool CallFunc_Less_IntInt_ReturnValue_1, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, double CallFunc_SelectFloat_ReturnValue, bool CallFunc_TryUpdateAccumulationInstance_ReturnValue, const struct FS_HazardAccumulation& K2Node_SetFieldsInStruct_StructOut_1, float CallFunc_GetFloatValue_ReturnValue, bool CallFunc_NearlyEqual_FloatFloat_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_Not_PreBool_ReturnValue_1, const struct FTimerHandle& CallFunc_K2_SetTimerDelegate_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, TScriptInterface<class IAccumulationAccessInterface> K2Node_DynamicCast_AsAccumulation_Access_Interface_1, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_TryUpdateAccumulationInstance_ReturnValue_1, double CallFunc_Subtract_DoubleDouble_B_ImplicitCast, double CallFunc_Add_DoubleDouble_B_ImplicitCast, float CallFunc_GetFloatValue_InTime_ImplicitCast, double CallFunc_NearlyEqual_FloatFloat_A_ImplicitCast);
	void RemovePreviousStatus(bool Material_Check, double Leeway, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_GetCurrentRealmTags_Success, const struct FGameplayTagContainer& CallFunc_GetCurrentRealmTags_RealmTags, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, TScriptInterface<class IAccumulationAccessInterface> K2Node_DynamicCast_AsAccumulation_Access_Interface, bool K2Node_DynamicCast_bSuccess, TArray<class FName>& CallFunc_Map_Keys_Keys, bool CallFunc_K2_IsValidTimerHandle_ReturnValue, class FName CallFunc_Array_Get_Item, class FName CallFunc_StatusToAccumulationName_ReturnValue, class FName CallFunc_StatusToAccumulationName_ReturnValue_1, const struct FS_HazardStatus& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FS_HazardAccumulation& CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_HasAllTags_ReturnValue, int32 CallFunc_GetNumGameplayTagsInContainer_ReturnValue, bool CallFunc_HasAllTags_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_GetNumGameplayTagsInContainer_ReturnValue_1, bool CallFunc_Greater_DoubleDouble_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue_1, bool K2Node_MathExpression_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_2, TScriptInterface<class IAccumulationAccessInterface> K2Node_DynamicCast_AsAccumulation_Access_Interface_1, bool K2Node_DynamicCast_bSuccess_1, class AActor* CallFunc_GetOwner_ReturnValue_3, const struct FS_HazardAccumulation& CallFunc_Map_Find_Value_2, bool CallFunc_Map_Find_ReturnValue_2, TScriptInterface<class IStatusEffectAccessInterface> K2Node_DynamicCast_AsStatus_Effect_Access_Interface, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_IsStatusEffectInstanceValid_ReturnValue, float CallFunc_GetTimeRange_MinTime, float CallFunc_GetTimeRange_MaxTime, bool K2Node_MathExpression_ReturnValue_1, double CallFunc_Multiply_DoubleDouble_ReturnValue, const struct FS_HazardAccumulation& K2Node_SetFieldsInStruct_StructOut, float CallFunc_TryGetAccumulationInstanceValue_OutValue, bool CallFunc_TryGetAccumulationInstanceValue_ReturnValue, bool CallFunc_TryUpdateAccumulationInstance_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue_1, class AActor* CallFunc_GetOwner_ReturnValue_4, TScriptInterface<class IStatusEffectAccessInterface> K2Node_DynamicCast_AsStatus_Effect_Access_Interface_1, bool K2Node_DynamicCast_bSuccess_3, float CallFunc_TryUpdateAccumulationInstance_NewValue_ImplicitCast, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast, double CallFunc_Greater_DoubleDouble_A_ImplicitCast);
	void SetupAccumulationHandle(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FS_HazardMaterial& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, TSoftObjectPtr<class UAccumulationDataAsset> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, TScriptInterface<class IAccumulationAccessInterface> K2Node_DynamicCast_AsAccumulation_Access_Interface, bool K2Node_DynamicCast_bSuccess, const struct FAccumulationHandle& CallFunc_TryAddAccumulationInstance_OutHandle, bool CallFunc_TryAddAccumulationInstance_ReturnValue, const struct FS_HazardAccumulation& K2Node_MakeStruct_S_HazardAccumulation);
	void OnAccumulationComplete(struct FAccumulationHandle& Handle, float Value, bool FoundActive, class AActor* CallFunc_GetOwner_ReturnValue, int32 Temp_int_Array_Index_Variable, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, TScriptInterface<class IAccumulationAccessInterface> K2Node_DynamicCast_AsAccumulation_Access_Interface, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Loop_Counter_Variable, TArray<struct FS_HazardAccumulation>& CallFunc_Map_Values_Values, const struct FS_HazardAccumulation& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, const struct FS_HazardAccumulation& K2Node_SetFieldsInStruct_StructOut, bool CallFunc_Less_IntInt_ReturnValue, float CallFunc_TryGetAccumulationInstanceValue_OutValue, bool CallFunc_TryGetAccumulationInstanceValue_ReturnValue, bool CallFunc_EqualEqual_AccumulationHandle_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_GreaterEqual_DoubleDouble_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, double CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast);
	void UpdateFloorState(class UNWXPhyiscalMaterial* Floor, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue);
	void ReceiveBeginPlay();
	void OnWadingUpdated(bool Apply);
	void OnSwimmingUpdated(bool Apply);
	void ExecuteUbergraph_BP_HazardMaterialComponent(int32 EntryPoint, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, TScriptInterface<class IAccumulationAccessInterface> K2Node_DynamicCast_AsAccumulation_Access_Interface, bool K2Node_DynamicCast_bSuccess, class AActor* CallFunc_GetOwner_ReturnValue_2, bool K2Node_CustomEvent_Apply_1, class ABP_Character_C* K2Node_DynamicCast_AsBP_Character, bool K2Node_DynamicCast_bSuccess_1, bool K2Node_CustomEvent_Apply);
};

}


