#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass BP_PlacerObject_CompositeBuilding.BP_PlacerObject_CompositeBuilding_C
class UBP_PlacerObject_CompositeBuilding_C : public UBP_StructurePlacerObject_C
{
public:

	static class UClass* StaticClass();
	static class UBP_PlacerObject_CompositeBuilding_C* GetDefaultObj();

	struct FGameplayAbilityTargetDataHandle GetPlacementTransform(class UObject* Structure, class ACharacter* Character, float OptionalDeltaRotationZ, float OptionalDeltaHeightZ, const struct FTransform& GroundTransform, const struct FRotator& PlacementRotation, const struct FVector& HitLocation, class ABP_Structure_Composite_C* StructureComposite, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, const struct FRotator& CallFunc_MakeRotatorForPlacement_ReturnValue, bool CallFunc_GetPlacementRaytraceHits_OutFoundHits, TArray<struct FHitResult>& CallFunc_GetPlacementRaytraceHits_OutHitResults, class ABP_Structure_Composite_C* K2Node_DynamicCast_AsBP_Structure_Composite, bool K2Node_DynamicCast_bSuccess, const struct FHitResult& CallFunc_Array_Get_Item, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, const struct FVector& CallFunc_BreakHitResult_Location, const struct FVector& CallFunc_BreakHitResult_ImpactPoint, const struct FVector& CallFunc_BreakHitResult_Normal, const struct FVector& CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class AActor* CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, class FName CallFunc_BreakHitResult_HitBoneName, class FName CallFunc_BreakHitResult_BoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_ElementIndex, int32 CallFunc_BreakHitResult_FaceIndex, const struct FVector& CallFunc_BreakHitResult_TraceStart, const struct FVector& CallFunc_BreakHitResult_TraceEnd, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& CallFunc_GetOrigin_StructureOrigin, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, const struct FTransform& CallFunc_AdjustZHeight_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FTransform& CallFunc_AddZHeightToPlacementTransform_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, const struct FGameplayAbilityTargetDataHandle& CallFunc_AbilityTargetDataFromTransform_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue_1, double CallFunc_Add_DoubleDouble_B_ImplicitCast, float CallFunc_AddZHeightToPlacementTransform_PlacementZOffset_ImplicitCast);
	bool FinalizePlacement(class UObject* Structure, class AController* Controller, struct FSnapPlacementTargetData& SnapData, class UBP_StructureCompositePiece_C* CurrentPiece, class ABP_Structure_Composite_C* StructureComposite, TScriptInterface<class IPlaceableEntityInterface> K2Node_DynamicCast_AsPlaceable_Entity_Interface, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TScriptInterface<class IStructureStateInterface> K2Node_DynamicCast_AsStructure_State_Interface, bool K2Node_DynamicCast_bSuccess_1, enum class EStructureState CallFunc_GetSchematicState_ReturnValue, const class FString& CallFunc_FinalizePlacement_Message, bool CallFunc_FinalizePlacement_ReturnValue, TScriptInterface<class IStructureStateInterface> K2Node_DynamicCast_AsStructure_State_Interface_1, bool K2Node_DynamicCast_bSuccess_2, TScriptInterface<class IStructureStateInterface> K2Node_DynamicCast_AsStructure_State_Interface_2, bool K2Node_DynamicCast_bSuccess_3, enum class EStructureState CallFunc_SetStructureSchematicState_ReturnValue, enum class EStructureState CallFunc_SetStructureSchematicState_ReturnValue_1, TScriptInterface<class IStructureStateInterface> K2Node_DynamicCast_AsStructure_State_Interface_3, bool K2Node_DynamicCast_bSuccess_4, class UStructureStateObject* CallFunc_GetStateObject_ReturnValue, bool CallFunc_InitializeOwningPlayer_Success, bool CallFunc_CanTransitionToConfirm_ReturnValue, class ABP_Structure_Composite_C* K2Node_DynamicCast_AsBP_Structure_Composite, bool K2Node_DynamicCast_bSuccess_5, TScriptInterface<class IStructureStateInterface> K2Node_DynamicCast_AsStructure_State_Interface_4, bool K2Node_DynamicCast_bSuccess_6, class UStructureCompositeComponent* CallFunc_GetCompositeComponent_ReturnValue, enum class EStructureState CallFunc_SetStructureSchematicState_ReturnValue_2, class UStructureCompositePiece* CallFunc_GetCompositePiece_ReturnValue, class UBP_StructureCompositePiece_C* K2Node_DynamicCast_AsBP_Structure_Composite_Piece, bool K2Node_DynamicCast_bSuccess_7, int32 CallFunc_GetPieceCount_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue);
	struct FStructurePlacementFeedback IsValidPlacement(class UObject* Structure, class AController* Controller, struct FGameplayAbilityTargetDataHandle& TargetData, class UBP_StructureCompositePiece_C* CurrentPiece, const TArray<class UObject*>& InvalidPieces, class ABP_Structure_Composite_C* CompositeStructure, const struct FStructurePlacementFeedback_Support& CallFunc_MakeSupportedSupportPlacementData_StructurePlacementFeedback_Support, const struct FStructurePlacementFeedback& CallFunc_GetValidPlacementFeedbackData_ReturnValue, bool CallFunc_InitializeOwningPlayer_Success, const struct FStructurePlacementFeedback_Collision& K2Node_MakeStruct_StructurePlacementFeedback_Collision, class ABP_Structure_Composite_C* K2Node_DynamicCast_AsBP_Structure_Composite, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, const struct FStructurePlacementFeedback_CompositeBuilding& K2Node_MakeStruct_StructurePlacementFeedback_CompositeBuilding, int32 Temp_int_Variable, const struct FStructurePlacementFeedback& K2Node_MakeStruct_StructurePlacementFeedback, int32 CallFunc_Add_IntInt_ReturnValue, class UStructureCompositeComponent* CallFunc_GetCompositeComponent_ReturnValue, TScriptInterface<class IPlaceableEntityInterface> CallFunc_IsValidPlacement_self_CastInput, const struct FStructurePlacementFeedback& CallFunc_IsValidPlacement_PlacementFeedbackData, class UStructureCompositePiece* CallFunc_GetCompositePiece_ReturnValue, class UBP_StructureCompositePiece_C* K2Node_DynamicCast_AsBP_Structure_Composite_Piece, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_GetPieceCount_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue);
	struct FTransform AdjustZHeight(class ABP_Structure_Composite_C* CompositeStructure, const struct FVector& PlacementLocation, const struct FTransform& CurrentTransform, const struct FVector& LPlacementLocation, const struct FTransform& LCurrentTransform, const struct FVector& LPlacementFoundationBounds, class ABP_Structure_Composite_C* LCompositeStructure, double LMaxZ, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TScriptInterface<class ICustomBoundsInterface> K2Node_DynamicCast_AsCustom_Bounds_Interface, bool K2Node_DynamicCast_bSuccess, TArray<class UObject*>& K2Node_MakeArray_Array, const struct FVector& CallFunc_GetBounds_Bounds, double CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double CallFunc_BreakVector_Z, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, const struct FVector& CallFunc_BreakTransform_Location_1, const struct FRotator& CallFunc_BreakTransform_Rotation_1, const struct FVector& CallFunc_BreakTransform_Scale_1, const struct FTransform& CallFunc_MakeTransform_ReturnValue, double CallFunc_BreakVector_X_1, double CallFunc_BreakVector_Y_1, double CallFunc_BreakVector_Z_1, const struct FVector& Temp_struct_Variable, const struct FVector& CallFunc_MakeVector_ReturnValue, TArray<struct FHitResult>& CallFunc_FindCornerHits_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue_1, const struct FHitResult& CallFunc_Array_Get_Item, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, const struct FVector& CallFunc_BreakHitResult_Location, const struct FVector& CallFunc_BreakHitResult_ImpactPoint, const struct FVector& CallFunc_BreakHitResult_Normal, const struct FVector& CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class AActor* CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, class FName CallFunc_BreakHitResult_HitBoneName, class FName CallFunc_BreakHitResult_BoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_ElementIndex, int32 CallFunc_BreakHitResult_FaceIndex, const struct FVector& CallFunc_BreakHitResult_TraceStart, const struct FVector& CallFunc_BreakHitResult_TraceEnd, int32 CallFunc_Array_Length_ReturnValue, double CallFunc_BreakVector_X_2, double CallFunc_BreakVector_Y_2, double CallFunc_BreakVector_Z_2, bool CallFunc_Less_IntInt_ReturnValue, double CallFunc_FMax_ReturnValue);
	void GetOrigin(class ABP_Structure_Composite_C* CompositeStructure, struct FVector* StructureOrigin, const TArray<class UBP_StructureCompositePiece_C*>& LFoundations, int32 FoundationCount, const struct FVector& OriginSum, class UObject* CurrentCompositePiece, TArray<class UBP_StructureCompositePiece_C*>& CallFunc_GetOwnedPiecesOfType_MatchingPieces, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Variable, bool CallFunc_IsValid_ReturnValue, TScriptInterface<class IStructureMeshInfoInterface> K2Node_DynamicCast_AsStructure_Mesh_Info_Interface, bool K2Node_DynamicCast_bSuccess, const struct FVector& CallFunc_GetMeshOrigin_LocalLocation, const struct FVector& CallFunc_GetMeshOrigin_WorldLocation, class UBP_StructureCompositePiece_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, const struct FVector& CallFunc_Divide_VectorInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, const struct FVector& CallFunc_Add_VectorVector_ReturnValue);
};

}


