#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass BPFL_Crafting.BPFL_Crafting_C
class UBPFL_Crafting_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class UBPFL_Crafting_C* GetDefaultObj();

	void CanOverrideSimilarInfusion(struct FInventoryEntry& Infusion, struct FInventoryEntry& Item, class UObject* __WorldContext, bool* OverrideOnly, bool Temp_bool_True_if_break_was_hit_Variable, const struct FInstanceData_AttributeModifiers& CallFunc_TryGetItemAttributeModifiers_Modifiers, enum class EGetResult CallFunc_TryGetItemAttributeModifiers_Branches, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_Not_PreBool_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, enum class EGetResult CallFunc_TryConstructItemAttributeModifier_Branches, const struct FInstancedItemAttributeModifier& CallFunc_TryConstructItemAttributeModifier_ReturnValue, int32 Temp_int_Array_Index_Variable, const struct FInstancedItemAttributeModifier& CallFunc_Array_Get_Item, bool K2Node_SwitchEnum_CmpSuccess_1, bool CallFunc_NotEqual_FItemAttributeModifierReference_ReturnValue, bool CallFunc_DoAttributeModifiersShareCharacteristic_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1);
	void DoItemsShareModifiers(struct FInventoryEntry& Item_A, struct FInventoryEntry& Item_B, class UObject* __WorldContext, bool* DoesShare, enum class EGetResult CallFunc_TryConstructItemAttributeModifier_Branches, const struct FInstancedItemAttributeModifier& CallFunc_TryConstructItemAttributeModifier_ReturnValue, enum class EGetResult CallFunc_TryConstructItemAttributeModifier_Branches_1, const struct FInstancedItemAttributeModifier& CallFunc_TryConstructItemAttributeModifier_ReturnValue_1, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_DoAttributeModifiersShareCharacteristic_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess_1);
	double GetDeltaTimer(double Clamped, double Base, double Modifer, class UObject* __WorldContext, double Delta_Result, bool CallFunc_NotEqual_DoubleDouble_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_1);
	void GetStepRefinementTimerLength(const struct FS_Crafting_Step_Definition& StepData, class UBP_CraftingStationComponent_C* CraftingStationComponent, const struct FCraftingRecipeReference& RecipeReference, class UObject* __WorldContext, double* Return_Value, double* Delta, float CallFunc_GetMinimumCraftingTimeAllowed_ReturnValue, bool CallFunc_IsValid_ReturnValue, double CallFunc_GetCurrentRefinementMod_Time, const struct FS_Crafting_Step_RefinementTimer& CallFunc_GetStructByType_OutStruct, bool CallFunc_GetStructByType_ReturnValue, double K2Node_MathExpression_ReturnValue, double CallFunc_Add_DoubleDouble_A_ImplicitCast, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast, double CallFunc_FClamp_Min_ImplicitCast, double CallFunc_GetDeltaTimer_ReturnValue, double K2Node_MathExpression_MinTime_ImplicitCast, double K2Node_MathExpression_TimerBase_ImplicitCast, double CallFunc_GetDeltaTimer_Base_ImplicitCast);
	void DoesPlayerHaveRecipeUnlocked(class AController* Controller, const struct FCraftingRecipeReference& RecipeReference, class UObject* __WorldContext, bool* bIsUnlocked, bool Temp_bool_Variable, bool CallFunc_IsValid_ReturnValue, TScriptInterface<class ISkillUnlockInterface> K2Node_DynamicCast_AsSkill_Unlock_Interface, bool K2Node_DynamicCast_bSuccess, const struct FSkillDataReference& CallFunc_MakeSkillDataReferenceFromCraftingRecipeReference_ReturnValue, bool CallFunc_HasSkillFullyUnlocked_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void GetRecipeTimeRequired(class UBP_CraftingStationComponent_C* CraftingStationComponent, struct FCraftingRecipeReference& RecipeReference, int32 CraftAmount, class UObject* __WorldContext, double* OutTimeRequired, double* OutDeltaTime, double BaseTraitsDelta, float RefinementModifier, const struct FCraftingRecipe& RecipeData, double CurrentTimeRequired, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, bool K2Node_SwitchEnum_CmpSuccess, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_Conv_IntToDouble_ReturnValue_1, const struct FDataTableRowHandle& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FS_Crafting_Step_Definition& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, double CallFunc_GetStepRefinementTimerLength_Return_Value, double CallFunc_GetStepRefinementTimerLength_Delta, double CallFunc_Multiply_DoubleDouble_ReturnValue_1);
	void IsRecipeMultiCraftable(const struct FCraftingRecipeReference& RecipeReference, class UObject* __WorldContext, bool* Success, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, const struct FGameplayTagQuery& CallFunc_MakeGameplayTagQuery_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, const struct FGameplayTagQuery& CallFunc_MakeGameplayTagQuery_ReturnValue_1, const struct FGameplayTagContainer& CallFunc_MakeGameplayTagContainerFromArray_ReturnValue, bool CallFunc_DoesContainerMatchTagQuery_ReturnValue, bool CallFunc_DoesContainerMatchTagQuery_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue);
	bool AreQuantityConstraintsSatisfied(const struct FCraftingConstraintSet& ConstraintSet, const struct FInventoryEntry& InputItem, class UObject* __WorldContext, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	bool AreCharacteristicConstraintsSatisfied(const struct FInventoryEntry& ItemEntry, TArray<struct FCharacteristicDataReference>& CharacteristicConstraints, class UObject* __WorldContext, const TArray<struct FCharacteristicDataReference>& ItemSecondaryCharacteristics, const struct FCharacteristicDataReference& ItemPrimaryCharacteristic, const struct FCharacteristicDataReference& CurrentConstraintToSatisfy, bool ConstraintSatisfied, int32 CallFunc_Array_Length_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable, bool CallFunc_Array_Contains_ReturnValue, TArray<struct FCharacteristicDataReference>& CallFunc_TryGetItemAdditionalCharacteristicsReference_CharacteristicsReference, enum class EGetResult CallFunc_TryGetItemAdditionalCharacteristicsReference_Branches, const struct FCharacteristicDataReference& CallFunc_TryGetItemPrimaryCharacteristicReference_CharacteristicReference, enum class EGetResult CallFunc_TryGetItemPrimaryCharacteristicReference_Branches, bool K2Node_SwitchEnum_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess_1, bool CallFunc_IsValid_ReturnValue, const struct FCharacteristicDataReference& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_EqualEqual_FCharacteristicDataReference_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void DoesActorHaveCraftingTraits(class AActor* Actor, TArray<struct FCraftingSlotTrait>& Traits, const struct FCraftingRecipe& CraftingRecipe, class UObject* __WorldContext, bool* Success, const struct FCraftingSlotTrait& CurrentEnvironmentalConstraint, class UAbilitySystemComponent* ActorASC, const struct FCraftingRecipeSlotType& EnvironmentalConstraintSlot, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, const class FString& CallFunc_GetDisplayName_ReturnValue, class FText CallFunc_Format_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_1, class FText CallFunc_Format_ReturnValue_1, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, TScriptInterface<class IGameplayTagAssetInterface> CallFunc_GetOwnedGameplayTags_self_CastInput, const struct FGameplayTagContainer& CallFunc_GetOwnedGameplayTags_TagContainer, bool CallFunc_IsValid_ReturnValue, bool CallFunc_HasAllTags_ReturnValue, class UAbilitySystemComponent* CallFunc_GetAbilitySystemComponent_ReturnValue, const struct FCraftingSlotTrait& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class FText CallFunc_Conv_NameToText_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_3, const struct FCraftingRecipeSlotType& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_2, class FText CallFunc_Format_ReturnValue_2, const class FString& CallFunc_Conv_TextToString_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_1);
	void GetDataForSlotType(const struct FDataTableRowHandle& SlotTypeRowHandle, class UObject* __WorldContext, bool* bSuccess, struct FCraftingRecipeSlotType* SlotTypeData, class FText CallFunc_Conv_NameToText_ReturnValue, const struct FCraftingRecipeSlotType& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, class FText CallFunc_Conv_ObjectToText_ReturnValue, bool CallFunc_IsDataTableStructType_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, bool CallFunc_IsValid_ReturnValue, class FText CallFunc_Format_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue);
	void GetCraftingRecipesForDisciplinesFromUnlocked(TArray<struct FGameplayTag>& RequestedDisciplines, const struct FS_UnlockedRecipes& UnlockedRecipes, class UObject* __WorldContext, TArray<struct FCraftingRecipeReference>* Recipes, const TArray<struct FCraftingRecipeReference>& LUnlockedRecipes, const struct FCraftingRecipeReference& CurrentRecipeID, const TArray<struct FCraftingRecipeReference>& FoundRecipes, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FCraftingRecipeReference& CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, TArray<struct FGameplayTag>& CallFunc_GetRecipeDisciplines_CraftingDisciplines, int32 CallFunc_Array_Add_ReturnValue, const struct FGameplayTagContainer& CallFunc_MakeGameplayTagContainerFromArray_ReturnValue, const struct FGameplayTagContainer& CallFunc_MakeGameplayTagContainerFromArray_ReturnValue_1, bool CallFunc_HasAnyTags_ReturnValue);
	void GetCraftingOutputPreview(const struct FCraftingRecipeReference& RecipeId, int32 Quantity, TArray<struct FInventoryEntry>& InputMaterials, class AActor* Crafter, class AActor* Station, class UObject* __WorldContext, TArray<struct FInventoryEntry>* PreviewItems, int32 ResultIndex, const TArray<class UItemProcessingDataAsset*>& ItemProcessing, const TArray<struct FInventoryEntry>& Preview, class UObject* CurrentResultItem, const TArray<struct FS_Crafting_Recipe_Result_Loaded>& LoadedCraftingOutputs, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, enum class EGetResult CallFunc_TryCreateCraftingContext_Branches, const struct FItemProcessingContext& CallFunc_TryCreateCraftingContext_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, TArray<struct FInventoryEntry>& K2Node_MakeArray_Array, bool CallFunc_GetCraftingOutputs_Success, TArray<class UCraftingResultObject*>& CallFunc_GetCraftingOutputs_Results, class UCraftingResultObject* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, TScriptInterface<class IItemProcessingObjectInterface> K2Node_DynamicCast_AsItem_Processing_Object_Interface, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_ProcessData_bSuccess, TArray<class UItemProcessingDataAsset*>& CallFunc_ProcessData_ReturnValue, class UItemProcessingDataAsset* CallFunc_Array_Get_Item_1, class UCrafting_Result_Items_DataAsset* K2Node_DynamicCast_AsCrafting_Result_Items_Data_Asset, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	void UpdateDynamicStructVariable(struct FDynamicTypedStructs& DynamicStruct, const struct FJsonStruct& Update, class UObject* __WorldContext, const struct FDynamicTypedStructs& CallFunc_UpdateDynamicStructs_DynamicStructOut);
	void GetCraftingStepsForRecipe(const struct FCraftingRecipeReference& RecipeId, class UObject* __WorldContext, bool* Success, TArray<struct FDataTableRowHandle>* RecipeSteps, TArray<struct FDataTableRowHandle>& K2Node_MakeArray_Array, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, bool K2Node_SwitchEnum_CmpSuccess);
	struct FCraftingRecipe GetRecipeFromHandle(const struct FDataTableRowHandle& RecipeHandle, class UObject* __WorldContext, bool* Success, const struct FCraftingRecipe& RecipeDefinition, const struct FCraftingRecipe& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	struct FS_Crafting_Step_Definition GetStepDefinitionFromHandle(const struct FDataTableRowHandle& StepHandle, class UObject* __WorldContext, bool* Success, const struct FS_Crafting_Step_Definition& StepData, const struct FS_Crafting_Step_Definition& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValidClass_ReturnValue, bool CallFunc_IsValidClass_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue);
	TArray<struct FCraftingRecipeReference> GetRecipeVariants(const struct FCraftingRecipeReference& RecipeId, class UObject* __WorldContext, bool* Success, TArray<struct FCraftingRecipeReference>& K2Node_MakeArray_Array, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, bool K2Node_SwitchEnum_CmpSuccess);
	struct FCraftingRecipeReference FindBestCraftingRecipeVariant(class AActor* Crafter, class AActor* CraftingStation, const struct FCraftingRecipeReference& BaseRecipeID, int32 RequestedQuantity, TArray<struct FInventoryEntry>& InputItems, class UObject* __WorldContext, bool* Success, const struct FCraftingRecipeReference& CurrentVariantID, const TArray<int32>& InputSlotQuantities, const TArray<class FName>& InputSlotItemIDs, int32 InputQuantity, const struct FCraftingRecipeReference& DiscoveredRecipe, int32 Temp_int_Array_Index_Variable, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_GetRecipeVariants_Success, TArray<struct FCraftingRecipeReference>& CallFunc_GetRecipeVariants_ReturnValue, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, const struct FCraftingRecipeReference& CallFunc_Array_Get_Item, bool K2Node_SwitchEnum_CmpSuccess, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe_1, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches_1, bool K2Node_SwitchEnum_CmpSuccess_1, bool CallFunc_IsRecipeSatisfied_ReturnValue, bool CallFunc_IsRecipeSatisfied_ReturnValue_1);
	bool IsRecipeVariant(const struct FCraftingRecipeReference& RecipeId, class UObject* __WorldContext, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, bool K2Node_SwitchEnum_CmpSuccess);
	TArray<struct FCraftingRecipeReference> GetCraftingRecipesForDisciplines(TArray<struct FGameplayTag>& RequestedDisciplines, class UObject* __WorldContext, const struct FDataTableRowHandle& CurrentRecipeID, const TArray<struct FDataTableRowHandle>& FoundRecipes, const struct FGameplayTagContainer& CallFunc_MakeGameplayTagContainerFromArray_ReturnValue, TArray<struct FCraftingRecipeReference>& CallFunc_FindAllCraftingRecipesWithDisciplines_ReturnValue);
	void GetRecipeDisciplines(const struct FCraftingRecipeReference& RecipeReference, class UObject* __WorldContext, TArray<struct FGameplayTag>* CraftingDisciplines, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, bool K2Node_SwitchEnum_CmpSuccess);
	bool IsConstraintSlotSatisfiedByNumber(const struct FCraftingRecipeReference& RecipeId, int32 ConstraintSlotNumber, const struct FInventoryEntry& InputItem, class UObject* __WorldContext, bool CallFunc_GetRecipeSlots_Success, TArray<struct FCraftingConstraintSlot>& CallFunc_GetRecipeSlots_ReturnValue, const struct FCraftingConstraintSlot& CallFunc_Array_Get_Item, bool CallFunc_IsConstraintSlotSatisfied_Success);
	void GetRecipeSlotCount(const struct FCraftingRecipeReference& RecipeId, class UObject* __WorldContext, bool* Success, int32* SlotCount, bool CallFunc_GetRecipeSlots_Success, TArray<struct FCraftingConstraintSlot>& CallFunc_GetRecipeSlots_ReturnValue, int32 CallFunc_Array_Length_ReturnValue);
	TArray<struct FCraftingConstraintSlot> GetRecipeSlots(const struct FCraftingRecipeReference& RecipeId, class UObject* __WorldContext, bool* Success, TArray<struct FCraftingConstraintSlot>& K2Node_MakeArray_Array, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, bool K2Node_SwitchEnum_CmpSuccess);
	void GetRecipeDisplayName(const struct FCraftingRecipeReference& RecipeId, class UObject* __WorldContext, class FText* Display_Name, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, bool K2Node_SwitchEnum_CmpSuccess);
	void GetCraftingOutputs(const struct FCraftingRecipeReference& RecipeId, int32 Quantity, class UObject* __WorldContext, bool* Success, TArray<class UCraftingResultObject*>* Results, const class FString& Suffix, const TArray<int32>& RecipeResultAmounts, const TArray<class FName>& RecipeResultIDs, int32 CurrentIndex, class FName CurrentResult, const TArray<struct FS_ItemWithQuantity>& ResultItems, const struct FCraftingRecipe& CallFunc_TryGetCraftingRecipe_CraftingRecipe, enum class EGetResult CallFunc_TryGetCraftingRecipe_Branches, bool K2Node_SwitchEnum_CmpSuccess);
	void GetUniqueItemQuantities(TArray<class FName>& ItemIDs, TArray<int32>& ItemQuantities, class UObject* __WorldContext, TArray<class FName>* UniqueIDs, TArray<int32>* TotalQuantities, int32 CurrentFoundValue, int32 CurrentFoundIndex, const TArray<int32>& Totals, const TArray<class FName>& FoundIDs, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue, class FName CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Get_Item_2, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Array_Get_Item_3, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Array_Find_ReturnValue);
	struct FCraftingRecipe GetCraftingRecipe(const struct FDataTableRowHandle& RecipeId, class UObject* __WorldContext, bool* Success, bool CallFunc_IsDataTableStructType_ReturnValue, const struct FCraftingRecipe& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue);
	void IsValidRecipe(const struct FDataTableRowHandle& RecipeId, class UObject* __WorldContext, bool* Success, bool CallFunc_IsValidRowHandle_IsValid, bool CallFunc_IsDataTableStructType_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void HasGameplayTagByName(class FName TagName, TArray<struct FGameplayTag>& TagArray, class UObject* __WorldContext, bool* Success, bool HasTag, int32 CallFunc_Array_Length_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, const struct FGameplayTag& CallFunc_Array_Get_Item, const class FString& CallFunc_GetDebugStringFromGameplayTag_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, int32 CallFunc_FindSubstring_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue);
	void IsConstraintSlotSatisfied(const struct FCraftingConstraintSlot& ConstraintSlot, const struct FInventoryEntry& InputItem, class UObject* __WorldContext, bool* Success, const struct FItemConstraintMatchData& CallFunc_IsItemConstraintMet_OutMatchData, enum class EGetResult CallFunc_IsItemConstraintMet_OutBranch, bool K2Node_SwitchEnum_CmpSuccess);
	void IsConstraintGroupStatisfied(TArray<struct FCraftingConstraintSet>& ConstraintGroup, const struct FInventoryEntry& InputItem, class UObject* __WorldContext, bool* Success, struct FCraftingConstraintSet* SatisfiedConstraintSet, bool* FoundMatchingSet, bool bMatchFound, const struct FCraftingConstraintSet& CurrentMatch, const struct FCraftingConstraintSet& CurrentConstraintSet, bool ConstraintGroupSatisfied, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FCraftingConstraintSet& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_IsConstraintSetSatisfied_Success, bool CallFunc_IsConstraintSetSatisfied_MatchesSet);
	void IsConstraintSetSatisfied(const struct FCraftingConstraintSet& ConstraintSet, const struct FInventoryEntry& InputItem, class UObject* __WorldContext, bool* Success, bool* MatchesSet, bool NonQuantitySatisfied, bool QuantitySatisfied, const struct FGameplayTagContainer& Traits, bool CallFunc_AreQuantityConstraintsSatisfied_ReturnValue);
};

}


