#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x50 (0x348 - 0x2F8)
// WidgetBlueprintGeneratedClass CF_UnlockAllProspects.CF_UnlockAllProspects_C
class UCF_UnlockAllProspects_C : public UCF_BaseCombo_C
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x2F8(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class UClass*>                        TalentControllerClasses;                           // 0x300(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                TalentContext;                                     // 0x310(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	struct FTalentsRowHandle                     UnlockTalentRow;                                   // 0x320(0x18)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTalentTreesEnum                      TalentTreesEnum;                                   // 0x338(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UCF_UnlockAllProspects_C* GetDefaultObj();

	void OnConstruction(int32 Temp_int_Variable, int32 Temp_int_Variable_1, const struct FTalentTreesEnum& CallFunc_IntToStruct_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, const struct FTalentTreesRowHandle& CallFunc_StructToRowHandle_ReturnValue, bool CallFunc_EqualEqual_FTalentTreesRowHandleFTalentTreesRowHandle_ReturnValue, bool CallFunc_EqualEqual_FTalentTreesRowHandleFTalentTreesRowHandle_ReturnValue_1, bool CallFunc_EqualEqual_FTalentTreesRowHandleFTalentTreesRowHandle_ReturnValue_2, bool CallFunc_EqualEqual_FTalentTreesRowHandleFTalentTreesRowHandle_ReturnValue_3, bool CallFunc_BooleanOR_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2, class UTalentTreesRow_C* CallFunc_Create_ReturnValue, int32 CallFunc_NumRows_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void OnTalentsSynced(bool CallFunc_FindTalentModelData_Found, const struct FTalentModelData& CallFunc_FindTalentModelData_TalentModelData, class FText CallFunc_Conv_StringToText_ReturnValue, int32 CallFunc_BreakTalentModelData_Rank, int32 CallFunc_BreakTalentModelData_MaxRank, enum class ETalentState CallFunc_BreakTalentModelData_State, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const class FString& CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, const class FString& CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1, class FText CallFunc_Conv_StringToText_ReturnValue_1, class FText CallFunc_Conv_StringToText_ReturnValue_2, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, bool K2Node_SwitchEnum_CmpSuccess, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_3, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_4, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_5, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_6, class FText CallFunc_Conv_StringToText_ReturnValue_3, class FText CallFunc_Conv_NameToText_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_7, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_8, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Conv_StringToText_ReturnValue_4, class FText CallFunc_Format_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_9, const class FString& CallFunc_Conv_TextToString_ReturnValue, class FText CallFunc_Conv_NameToText_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_10, class FText CallFunc_Conv_NameToText_ReturnValue_2, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_11, class FText CallFunc_Format_ReturnValue_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_2, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, class FText CallFunc_Format_ReturnValue_2, const class FString& CallFunc_Conv_TextToString_ReturnValue_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class AIcarusPlayerController* CallFunc_GetIcarusPlayerController_Controller);
	void TryUnlockAllProspectTalents(const struct FTalentTreesEnum& Enum, int32 NumberOfProspectsUnlocked, int32 TotalProspectsFound, int32 NewProspectsUnlocked, int32 Temp_int_Loop_Counter_Variable, const struct FTalentTreesEnum& CallFunc_MakeTalentTreesEnum_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, TArray<struct FTalentsRowHandle>& CallFunc_GetAllTalentRowHandlesOfType_Rows, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Variable, const struct FTalentsRowHandle& CallFunc_Array_Get_Item, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, int32 Temp_int_Variable_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, const class FString& CallFunc_Conv_TextToString_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, class AIcarusPlayerController* CallFunc_GetIcarusPlayerController_Controller, class AIcarusPlayerState* CallFunc_GetIcarusPlayerState_ReturnValue, class FText CallFunc_Conv_NameToText_ReturnValue, class FText CallFunc_Conv_NameToText_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_3, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_4, class FText CallFunc_Conv_StringToText_ReturnValue, class UTalentControllerComponent* CallFunc_GetTalentControllerForTalent_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_5, bool CallFunc_IsValid_ReturnValue, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_1, class FText CallFunc_Format_ReturnValue_1, TScriptInterface<class ITalentControllerInterface> CallFunc_UnlockNextTalentRank_self_CastInput, bool CallFunc_UnlockNextTalentRank_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, TScriptInterface<class ITalentControllerInterface> CallFunc_GetModel_self_CastInput, class UTalentModelInterface* CallFunc_GetModel_ReturnValue, bool CallFunc_IsTalentUnlocked_ReturnValue, const struct FTalentModelData& CallFunc_GetTalentState_OutData, bool CallFunc_GetTalentState_ReturnValue, int32 CallFunc_BreakTalentModelData_Rank, int32 CallFunc_BreakTalentModelData_MaxRank, enum class ETalentState CallFunc_BreakTalentModelData_State, bool CallFunc_GreaterEqual_IntInt_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_6, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_2, class FText CallFunc_Format_ReturnValue_2, const class FString& CallFunc_Conv_TextToString_ReturnValue_2);
	void GetAllTalentRowHandlesOfType(const struct FTalentTreesEnum& TalentTreeEnum, TArray<struct FTalentsRowHandle>* Rows, const TArray<struct FTalentsRowHandle>& AllRows, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, class AIcarusPlayerController* CallFunc_GetIcarusPlayerController_Controller, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, class AIcarusPlayerState* CallFunc_GetIcarusPlayerState_ReturnValue, int32 Temp_int_Variable, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_2, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, TArray<class UTalentControllerComponent*>& CallFunc_GetTalentControllers_ReturnValue, class UTalentControllerComponent* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue_1, class UClass* CallFunc_GetObjectClass_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_ClassIsChildOf_ReturnValue, TScriptInterface<class ITalentControllerInterface> CallFunc_GetModel_Const_self_CastInput, class UTalentModelInterface_Const* CallFunc_GetModel_Const_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, TArray<struct FTalentsRowHandle>& CallFunc_GetTalents_ReturnValue, const struct FTalentsRowHandle& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, const struct FTalent& CallFunc_GetTalentsStruct_Talents, enum class EValid CallFunc_GetTalentsStruct_Paths, bool K2Node_SwitchEnum_CmpSuccess, const struct FTalentTreesEnum& CallFunc_RowHandleToStruct_ReturnValue, bool CallFunc_EqualEqual_EnumEnum_ReturnValue);
	void FindTalentModelData(const struct FTalentsRowHandle& TalentRow, bool* Found, struct FTalentModelData* TalentModelData, class AIcarusPlayerController* CallFunc_GetIcarusPlayerController_Controller, bool CallFunc_IsValid_ReturnValue, class AIcarusPlayerState* CallFunc_GetIcarusPlayerState_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UTalentControllerComponent* CallFunc_GetTalentControllerForTalent_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, TScriptInterface<class ITalentControllerInterface> CallFunc_GetModel_Const_self_CastInput, class UTalentModelInterface_Const* CallFunc_GetModel_Const_ReturnValue, const struct FTalentModelData& CallFunc_GetTalentState_OutData, bool CallFunc_GetTalentState_ReturnValue);
	void Construct();
	void HandleExecute(class UUserWidget* Widget, int32 Amount);
	void ExecuteUbergraph_CF_UnlockAllProspects(int32 EntryPoint, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class AIcarusPlayerController* CallFunc_GetIcarusPlayerController_Controller, class UUserWidget* K2Node_Event_Widget, int32 K2Node_Event_Amount, class UTalentTreesRow_C* K2Node_DynamicCast_AsTalent_Trees_Row, bool K2Node_DynamicCast_bSuccess, const struct FTalentTreesEnum& CallFunc_RowHandleToStruct_ReturnValue);
};

}


